# -*- coding: utf-8 -*-
"""Log-Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12dgraL6xCUNlvtRpdrYWhOWRD9wM5Z3f
"""

def analisar_clima():

  soma_temperaturas = 0.0
  dias_quentes = 0
  alerta_extremo = False

  for dia in (1, 2, 3, 4, 5, 6, 7):
    print("Digite a temperatura do dia ", dia, ":")
    temp = float(input("temperatura: "))
    soma_temperaturas = soma_temperaturas + temp
  if temp > 35.0:
      dias_quentes = dias_quentes + 1

  if dias_quentes >= 2:
    alerta_extremo = True
    media_temp = soma_temperaturas / 7
    print("Média semanal: ", media_temp)
    print(f"Dias acima de 35C: {dias_quentes}")

  if alerta_extremo == True:
    print("CUIDADO: Condições climáticas perigosas detectadas!")
  else:
    print("Clima dentro da normalidade operacional")

analisar_clima()