# -*- coding: utf-8 -*-
"""Logica-para-Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12dgraL6xCUNlvtRpdrYWhOWRD9wM5Z3f
"""

def processar_vendas():
  total_compra = 0.0
  itens_comprados = 0



  try:
    print("Quantos produtos diferentes foram comprados?:")
    quantidade_tipos = int(input("Quantidade de tipos: "))

    for i in range(quantidade_tipos):

      print(f"\n Produto {i+1}")
      nome = input("Nome do produto: ")
      preco = float(input("Preço do produto: "))
      quantidade = int(input("Quantidade do produto: "))

    if preco <= 0 or quantidade <= 0:
      print(f"Erro: Valores inválidos para {nome}")
    else:
        subtotal = preco * quantidade
        total_compra += subtotal
        itens_comprados += quantidade

    if total_compra > 500.00:
      total_final = total_compra * 0.90
      print("\nDesconto de 10% aplicado!")
    elif total_compra >= 200.00:
      total_final = total_compra * 0.95
      print("\nDesconto de 5% aplicado!")
    else:
      total_final = total_compra
    print("-" * 30)
    print(f"Resumo: {itens_comprados} itens. Total a pagar: R$ {total_final:.2f}")

  except ValueError:

    print("\nErro: Por favor, digite apenas números para quantidades e preços.")

processar_vendas()